### ISSUE TITLE
Need update to support updated API base path "/v1"

### ISSUE THREAD

**Issue by ryanmatthews** [J-Swift/thegamesdb-swagger-client-go#1]
Per this post "https://forums.thegamesdb.net/viewtopic.php?f=5&t=352" the developers are updating and moving the API under /v1

**Comment by J-Swift** [comment]
Thanks for the heads up. I've got a fix for this in place but waiting for TheGamesDB dev to get back to me on [a related change](https://github.com/TheGamesDB/TheGamesDBv2/issues/19)

**Comment by J-Swift** [comment]
@ryanmatthews this should be fixed now. let me know if you test it and it doesn't work
